version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/argo-applications" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/infrastructure" 
    schedule:
      interval: "weekly"
