version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/argo-applications" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule" 
    directory: "/infrastructure/argocd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule" 
    directory: "/infrastructure/rabbitmq"
    schedule:
      interval: "weekly"
