apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/freberg/pine-cluster
    targetRevision: HEAD
    path: argo-applications
    directory:
      exclude: kubernetes-dashboard.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
