apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 5Gi
