---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    discord_token: AgBmtbkqyvKMnahhTUCn9qKw3OBEepdWnyJ8j1JlcQVWfrrWkrKef5QL25x9PKh0s+RE57ehKFlO3AQoR925WiQQFQbRkgHFll50zsy5409/wc4dEPiOuo+Fuqr3wIqHMY/6Erx31HHOiDxmMKC/FHlVA8KpP1Jq00ZVBWaBKtM/L49X5g+FHGEkh5yGj0+naLD44e4aVZUy3CxAzDT7BqZSGZYhloGQbbHkRCU4iZTd45gK93XfposmQghXvVq9hroQleDnHbGoSsjrZ78AGlXZ95QPM8T5+k8YpDn2mkhpLrSVKDqWOtDPAWbgQoYovFjqWdJKLGqUqj6NC0w+vB+4iMOqNiT0tlcDn4gSKNjbL6hUwZ6VphPSnMUjtZsQwJ95U2OtEuwWpFONgRwjHh0F5j7AFQlB8QKk0kIbeDF0hT+J9xrCLB60ftqN9XxIw6IsUJqRNaBH6tbYybelaIl0188/EwgRFpP60CqeZK6kwpPN9hIFxPG0bFaoOY3s5a98f82rYp1nJQutBXuHZUQKfi8tAOiKo1q40xXFN6GGAO4zu/ll8DutG+dZGkQr5WC7dY/s2VkR+hSHZDCimx5W7jtNsSjTdgSsXCjrD2D9Zj8Q7inL5srl5AXdVY6ODdJb6c6nWwkI1NVtNAbE8jl8m6+NKY2ykFaDPjhQaI2Isf0MC3YZXHobtKBhDCHefCC7rpcHlKaMWFZr94OZaZDvsHUoliuG0b0d+faMip1JRxwLcZKA8Kzk7nc52Hhj+sP0JbHh6OI3YpQXUBAWni7cp5KxP0JGE4+j0zt7Czfi5OIDup+5cbfgRk4Low8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: renovate-secret
      namespace: renovate
