---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    renovate-token: AgCOAhy2cckbV6wluLPiLvWC9Ix3hCYKtU0m1gCJu+ULXb49l7YU8PXw/7tFoHnIHPfcJ0X3GpuOjIDPFHqdR/Tt75+mFJtwIpJc9FdB0mNYWQPhLLRhY27SKFk9klPtTss5sN1oJ1lH51LL+rvTlE7yHSNLE8pYEtQ9DXWc5gAt7O1Arh1QS/g7+CnWZtOoBOKCtAjZgvyODv94vqlFoQUnv/UaTGA5b/+rCYgJlj9Qc2Enmc0MIqeogQ/Dx5hifhLZGqaBzxk/5PwWhPXIXk6ES6Dpz58wxwITDg58rEe+w+FSduP6UMiinvkvjIBF+Z8P6Ft17aHz5c3XhJETWLmE2FYfc08kPL6PwE4KEtfnQYHFbfXyd9TGazkS8EMi0Y/pvgMrgUswIzDG9zTqJJZZHEKex/mRc0DMBzDw30RLSav1oLeB4ByDBpbhq2dy0f9meHNw1jfMq4ALGg8ftOktrM5vuDv6B+CPXZk7DNOuiVJNJPmydtfDB9Hw3BhiWJZQ8FsWFVEFkUwS/dRCEOvJuuJ2JnfTA4hDN3oCnulT+HN1Lgs3lxE1P9HP5/TLKiY61N4CktcwXXgkp0QsIVHsQ3xvsypF2aDi2VFjhXneqoUYcMaug6BNIS3l7EUic0/a6rv+hI+QCToATj+b3etMiLqYITCx0Z4tWDConr2tV/+YoZ+sn0TmVUvWpRY7LJZFQirqdy9rd8Q4EJ5eTNyHU5OzndLDHeGJSV+hS9Z06iyD1VzCqefllqMUGddf3seSKqgt66SO6Aa2mTiXzcxQZZlhaxR9KSOn5WlXFkDOvlq1nEe4yEp7mNXPvoE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: renovate-secret
      namespace: renovate
