---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    renovate-token: AgBp0LTSBovrMcLtXx9jgWoHjSjsidnNUIG2qzfkabkdZT0r2WwqXDKanJDb+uRDSBiHTyWPh89SivBvWeQprDN2wKRD258KEjLL1pnnpoGqBusMXzAT5NvCk+Q8xwqHJlhvZ14nCaEp8uQSAf/TSmxVZwU8JjOFVBMu92h3Nysch1DEQGT2Flt7rYF8tGcHt6sIAZis3DZOgwtDc1cVLsX+bfUEmU/gG0bzL0cpzhnfoCokNDHRForcEL79Pp0EQr7kx5QUqmgSP53CieTyfO7hy0h3O7To0tPVbQWA0hbS4DolUfnf8E3/qzt68vnNARoctDZPAXdQCUeovRKYbEJWBhabvS6g/5Bx4dfPn5mLwHarDlWzG6QYt1gqTNR7nauhbB9H4uoqTOMKjpF9yhohjuPEz6p+Ji96qPaZ7nO6036xv+/iiThh/cuATR1QNZ7lw9ujdYgQmeHWf43yzk5QnXGlL6JFyqNnEiKNcHHoJoJaZ+nt2/K3RzwIO/1okOgycViqdXEhFIs6YqT/9YcDXKI95+MvD7vvEXv90ALOq4lfWVjvsYI5zYg9VL9howKchfKF2fRaR/O/xXhY+iOJ13fPZK2Xs5DQbSKRer886U/mtTURXHJYCeduvGcqLlXYXXbHhg2EMBmzGWnkTbBLcoQpXYtRnuO9m3HKkmAnkSTQeaP38ZPoHhSGHXWPguskIfilO32hf7wBiY4smsD5c1jFd6mNP+ro05ysO6FbAR1atOnXGdlbejxRaUoriC2guVQASNOSKBE73K0vEjh3nzmdRMSmybMsaLMQDZKtlIY9aK/zyg9rZqbm+NQ=
  template:
    metadata:
      name: renovate-secret
      namespace: renovate
