apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq-system

commonAnnotations:
  app.kubernetes.io/version: "v2.16.1" 

resources:
- https://github.com/rabbitmq/cluster-operator/releases/download/v2.16.1/cluster-operator.yml 
