apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.19.1
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: 'https://github.com/ebrianne/cert-manager-webhook-duckdns.git'
      path: deploy/cert-manager-webhook-duckdns
      targetRevision: v1.2.3
      helm:
        values: |
          clusterIssuer:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
