apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.9.1
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            createDefaultDiskLabeledNodes: true
            defaultDataPath: "/mnt/ssd/longhorn"

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
