apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.11.0
      helm:
        values: |
          # 1. memory leak hotfix - https://github.com/longhorn/longhorn/issues/12573
          image:
            longhorn:
              manager:
                tag: v1.11.0-hotfix-1
              instanceManager:
                tag: v1.11.0-hotfix-1

          preUpgradeChecker:
            jobEnabled: false
            upgradeVersionCheck: false # delete when removing hotfix
          global:
            tolerations:
              - key: "node-role.kubernetes.io/master"
                operator: "Equal"
                value: ""
                effect: "NoSchedule"
          defaultSettings:
            taintToleration: "node-role.kubernetes.io/master:NoSchedule"
            createDefaultDiskLabeledNodes: true
            defaultDataPath: "/mnt/ssd/longhorn"

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - ServerSideApply=true
