apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/freberg/pine-cluster
    targetRevision: HEAD
    path: infrastructure/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
