- name: "Install prerequisites on all cluster nodes"
  hosts: pine_cluster
  tags: common
  become: yes
  tasks:
    - name: "Install prerequisites packages"
      apt:
        name:
          - open-iscsi
          - nfs-common
          - cryptsetup
          - dmsetup

- name: "Prepare storage nodes"
  hosts: pine_cluster_storage
  tags: storage
  become: yes
  tasks:
    - name: "Install storage node prerequisites packages"
      apt:
        name:
          - xfsprogs
    - name: "Create bind mount entry for Longhorn"
      lineinfile:
        path: /etc/fstab
        line: "/mnt/ssd/longhorn /mnt/ssd/longhorn none bind 0 0"
        state: present
        insertafter: EOF

- name: "Prepare master nodes"
  hosts: pine_cluster_server
  become: yes
  tasks:
    - name: "Set GOMEMLIMIT for k3s"
      lineinfile:
        path: /etc/default/k3s
        line: "GOMEMLIMIT=1200MiB"
        create: yes
        owner: root
        group: root
        mode: '0644'
